name: Build and Deploy to Google Compute Engine

on:
  push:
    branches:
    - 'master'

env:
  PROJECT_ID: 	global-pagoda-368419
  GCE_INSTANCE: instance-1  # TODO: update to instance name
  GCE_INSTANCE_ZONE: us-central1-a # TODO: update to instance zone
jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest

    # Add "id-token" with the intended permissions.
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - uses: google-github-actions/setup-gcloud@main
      with:
        version: '276.0.0'
        service_account_email: "git-deploy@primeval-sweep-238715.iam.gserviceaccount.com"
        service_account_key: ${{ secrets.GCPDEPLOY }}
        export_default_credentials: true
    - name: auth login
      run:  gcloud auth login
    - name:  Deploy static site to google storage
      run: gcloud compute instances list    

